name: Make a Release and Deploy on GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - 'closed'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install and build
        run: |
          npm ci
          npm run build -- --prod
          npm run build:lib

      - name: Beta release using semantic-release
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy on GiHub Pages using angular-cli-ghpages
      - run: npm run deploy -- --no-silent --name="mr. Dharmen's Bot" --email=shhdharmen@gmail.com
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
