name: Test, Build and Publish a beta version

on:
  push:
    branches: [development]
  pull_request:
    types:
      - "closed"
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install, lint, test and build
        run: |
          npm ci
          npm run lint
          npm run build -- --prod
          npm test
          npm run build:lib

      - name: Beta release using semantic-release
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
